### ISSUE TITLE
VerifyBytes() to CalcHash() causes not compiling webchain-pool

### ISSUE THREAD

**Issue by fjluquerodriguez** [webchain-network/cryptonight#1]
github.com/webchain-network/webchain-pool/proxy
proxy/miner.go:30: hasher.VerifyBytes undefined (type *cryptonight.Cryptonight has no field or method VerifyBytes)
proxy/miner.go:34: hasher.VerifyBytes undefined (type *cryptonight.Cryptonight has no field or method VerifyBytes)
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lukaszmatczak** [comment]
I've merged 'vardiff' branch to master. Now it should compile without errors.
